### ISSUE TITLE
Enum fails

### ISSUE THREAD

**Issue by joabakk** [tkurki/signalk-zones#6]
I know this is a demo, but I get this error:
instance.configuration.zones[0].key is not one of enum values: navigation.courseOverGroundTrue,navigation.speedThroughWater

**Comment by tkurki** [comment]
Sounds like you are using an old version, as I believe the error message is from this https://github.com/SignalK/signalk-zones/commit/3464df39b8011cf06e69e0fcad93b70b32d18761#diff-168726dbe96b3ce427e7fedce31bb0bcR26 ,  which is now replaced by keys generated from the real schema.

I appreciate any and all error reports. Just make sure you are using the latest version.

**Comment by joabakk** [comment]
You are right again. Sorry I´m learning the ropes with npm
