### ISSUE TITLE
TypeError: Cannot read property 'reduce'

### ISSUE THREAD

**Issue by joabakk** [tkurki/signalk-zones#7]
Just updated to the latest from npm install git://...
I still get errors, this time it is:
`TypeError: Cannot read property 'reduce' of undefined
    at Object.plugin.start (/home/pi/signalk-server-node/node_modules/signalk-zones/index.js:95:33)`

**Comment by tkurki** [comment]
Fixed by c19a884331c01fd584ddc45b2b331ab405f1519b
